OpenAI:
  icon_url: 'https://storage.yandexcloud.net/data-genapi-wcu/icons-llm/openai.svg'
  networks:
    - llm_id: 'gpt-4o'
      models:
        - title: 'GPT-4 Omni'
          name: gpt-4o-2024-08-06
          max_tokens: 4096
          context_window: 128000
          input_price: 0.5 ₽
          output_price: 2.0 ₽
    - llm_id: 'gpt-4-1'
      models:
        - title: 'GPT-4.1 '
          name: gpt-4.1
          max_tokens: 33000
          context_window: 1050000
          input_price: 0.4 ₽
          output_price: 1.6 ₽
        - title: 'GPT-4.1 mini'
          name: gpt-4.1-mini
          max_tokens: 33000
          context_window: 1050000
          input_price: 0.01 ₽
          output_price: 0.4 ₽
        - title: 'GPT-4.1 nano'
          name: gpt-4.1-nano
          max_tokens: 33000
          context_window: 1050000
          input_price: 0.0025 ₽
          output_price: 0.01 ₽
    - llm_id: 'o3'
      models:
        - title: 'o3'
          name: o3-2025-04-16
          max_tokens: 4096
          context_window: 200000
          input_price: 3.0 ₽
          output_price: 12.0 ₽
        - title: 'o3-mini '
          name: o3-mini
          max_tokens: 4096
          context_window: 200000
          input_price: 1.65 ₽
          output_price: 6.6 ₽

xAI:
  icon_url: 'https://storage.yandexcloud.net/data-genapi-wcu/icons-llm/XAI.png'
  networks:
    - llm_id: 'grok-3'
      models:
        - title: 'Grok 3'
          name: grok-3-beta
          max_tokens: 131072
          context_window: 131072
          input_price: 0.6 ₽
          output_price: 3.0 ₽
        - title: 'Grok 3 mini'
          name: grok-3-mini-beta
          max_tokens: 131072
          context_window: 131072
          input_price: 0.6 ₽
          output_price: 0.1 ₽

DeepSeek:
  icon_url: 'https://storage.yandexcloud.net/data-genapi-wcu/icons-llm/deepseek.png'
  networks:
    - llm_id: 'deepseek-v3'
      models:
        - title: 'DeepSeek v3'
          name: deepseek-v3
          max_tokens: 4096
          context_window: 64000
          input_price: 0.2 ₽
          output_price: 1.0 ₽
    - llm_id: 'deepseek-r1'
      models:
        - title: 'DeepSeek r1'
          name: deepseek-r1
          max_tokens: 4096
          context_window: 64000
          input_price: 0.2 ₽
          output_price: 1.0 ₽

Perplexity:
  icon_url: 'https://storage.yandexcloud.net/data-genapi-wcu/icons-llm/perplexityai.png'
  networks:
    - llm_id: 'perplexity'
      models:
        - title: 'Perplexity sonar'
          name: sonar
          max_tokens: 4096
          context_window: 128000
          input_price: 0.4 ₽
          output_price: 0.4 ₽

Claude:
  icon_url: 'https://storage.yandexcloud.net/data-genapi-wcu/icons-llm/claude.webp'
  networks:
    - llm_id: 'claude'
      models:
        - title: 'Haiku 3.5'
          name: claude-3-5-haiku-20241022
          max_tokens: 4096
          context_window: 200000
          input_price: 0.4 ₽
          output_price: 1.1 ₽
        - title: 'Sonnet 3.5'
          name: claude-3-5-sonnet-20240620
          max_tokens: 4096
          context_window: 200000
          input_price: 0.8 ₽
          output_price: 3.0 ₽
        - title: 'Sonnet 3.7'
          name: claude-3-7-sonnet-20250219
          max_tokens: 4096
          context_window: 200000
          input_price: 0.8 ₽
          output_price: 3.0 ₽